### ISSUE TITLE
Instantly out of memory

### ISSUE THREAD

**Issue by BjornTheProgrammer** [tuupola/pico_effects#3]
I was running pico_effects on my raspberry pi pico, and with the settings that I enabled for my 480x320 ILI9488, it ran out of memory almost instantly.

Here is a screenshot of the output and settings.

<img width="1440" alt="Screen Shot 2022-09-19 at 2 01 49 AM" src="https://user-images.githubusercontent.com/75190918/190984607-0c1775e1-ede4-4b56-8b61-678c9afe77f3.png">

Is there any way to get this to work with my screen? Maybe it would be possible by just storing the memory in smaller segments, and writing in those segments?

The picture below shows the same thing after closing the rotozoom with different settings.

<img width="1440" alt="Screen Shot 2022-09-19 at 2 08 40 AM" src="https://user-images.githubusercontent.com/75190918/190985097-4580c0a2-0d00-4491-832d-e93e39bfa9aa.png">

Here is the UART output.

```
[HAGL HAL] Initialising double buffered display.
[HAGL HAL] Initialising SPI.
[HAGL HAL] Baudrate is set to 66500000.
[HAGL HAL] clk_peri 133000000.
[HAGL HAL] clk_sys 133000000.
[HAGL HAL] Inverting display.
[HAGL HAL] initialising DMA.
[HAGL HAL] Allocated back buffer to address 20001418.
METABALLS at 0 fps / 0 kBps
Closing metaballs.
Initialising plasma.
PLASMA at 32 fps / 3609 kBps
Closing plasma.
Initialising rotozoom.
ROTOZOOM at 10 fps / 1196 kBps
Closing rotozoom.
Initialising deform.

*** PANIC ***

Out of memory
```

**Comment by BjornTheProgrammer** [comment]
I've actually already figured out what the issue was, the MIPI_DISPLAY_SPI_CLOCK_SPEED_HZ flag. After I disabled that it began to work, but not for my screen size, only the 240x240, but it still panics after 30 seconds for the 240x240

**Comment by tuupola** [comment]
Pico does not have memory to run all the demos with double or triple buffering with 480x320 resolution. You need to use single buffering but that is of course super slow. I don't remember exactly what was the maximum resolution Pico had memory to run all effects. 

You can always configure your display to use some other resolution. For example Pimoroni Display Pack is 135x240 and it can run the demos both double and triple buffered. I think there should be enough memory to run the Deform effect double buffered with 240x240 resolution but maybe I remember wrong.

For the `MIPI_DISPLAY_SPI_CLOCK_SPEED_HZ` you should find the maximum setting your display driver chip can use without  clitches.  When you commented it out it used the default value of 64000000. Something like 48000000 is considered safe but all my boards can run 64000000 and higher.

**Comment by BjornTheProgrammer** [comment]
Sick! I actually got it to work with single buffering, still get a PANIC a bit after deform, I assume a memory leak of some sort is in the source code, but it works! I just hadn't realized that I needed to specify HAGL_HAL_USE_SINGLE_BUFFER even though it was the default.

**Comment by tuupola** [comment]
If you just want to test your larger display you could check:

https://github.com/tuupola/pico_gfx

There is nothing there in the demos themselves which use lots of memory.

**Comment by tuupola** [comment]
@BjornTheProgrammer You could also try the new `HAGL_HAL_PIXEL_SIZE` setting. I tested and I can run the demos with 320x240 display. Note that it will not work together with `HAGL_HAL_USE_DMA` at the moment.

```c
target_compile_definitions(firmware PRIVATE
  HAGL_HAL_USE_DOUBLE_BUFFER
  HAGL_HAL_DEBUG
  HAGL_HAL_PIXEL_SIZE=2
)
```

**Comment by BjornTheProgrammer** [comment]
Appreciate it, I will try it out if memory continues to be an issue!
