### ISSUE TITLE
I'm using a 160*128(128*160) ST7735 screen. Having problem(s) to display properly

### ISSUE THREAD

**Issue by eugnio1** [tuupola/pico_effects#6]
![problem](https://user-images.githubusercontent.com/125184176/218313894-3b964748-f5db-4f94-b3ac-d270521ad44d.jpg)
.cmake I'm using

```
target_compile_definitions(firmware PRIVATE
    MIPI_DISPLAY_PIN_DC=8
    MIPI_DISPLAY_PIN_CS=9
    MIPI_DISPLAY_PIN_CLK=10
    MIPI_DISPLAY_PIN_MOSI=11
    MIPI_DISPLAY_PIN_RST=12
    MIPI_DISPLAY_PIN_BL=13
    MIPI_DISPLAY_PIN_MISO=-1

    MIPI_DISPLAY_SPI_PORT=spi1
    MIPI_DISPLAY_SPI_CLOCK_SPEED_HZ=62500000
    MIPI_DISPLAY_PIXEL_FORMAT=MIPI_DCS_PIXEL_FORMAT_16BIT

    MIPI_DISPLAY_WIDTH=160
    MIPI_DISPLAY_HEIGHT=128
    MIPI_DISPLAY_OFFSET_X=2
    MIPI_DISPLAY_OFFSET_Y=2

    # MIPI_DISPLAY_WIDTH=128
    # MIPI_DISPLAY_HEIGHT=128
    # MIPI_DISPLAY_OFFSET_X=2
    # MIPI_DISPLAY_OFFSET_Y=2

    MIPI_DISPLAY_INVERT=0
)
```

**Comment by tuupola** [comment]
You have picture and correct looking colors so you are close. Looking at the photo it looks like your offsets should be 0 and display dimensions are swapped. Try something like:

```
MIPI_DISPLAY_OFFSET_X=0
MIPI_DISPLAY_OFFSET_Y=0
MIPI_DISPLAY_WIDTH=128
MIPI_DISPLAY_HEIGHT=160
```
If that does not help make sure all wiring, especially CLK is working properly. You could also try lower the SPI speed. Also double check that the panel dimensions are correct.

**Comment by eugnio1** [comment]
Thanks it works fine now!!
![IMG_2332](https://user-images.githubusercontent.com/125184176/218467844-7f945376-7ea1-46e7-a2e1-88825033d36b.jpg)
I changed the code a bit find out that when offset <=0 works fine and I did get the height and width messed up
