### ISSUE TITLE
Having a compile error with the ST7735

### ISSUE THREAD

**Issue by nicoverduin** [tuupola/pico_effects#7]
When I compile I get this error:

D:/vsarm/school/pico_effects/main.c: In function 'main':
D:/vsarm/school/pico_effects/main.c:238:31: error: incompatible type for argument 1 of 'busy_wait_until'
  238 |         busy_wait_until(start + US_PER_FRAME_60_FPS);
      |                         ~~~~~~^~~~~~~~~~~~~~~~~~~~~
      |                               |
      |                               uint64_t {aka long long unsigned int}
In file included from D:/vsarm/sdk/pico/pico-sdk/src/common/pico_time/include/pico/time.h:11,
                 from D:/vsarm/sdk/pico/pico-sdk/src/common/pico_stdlib/include/pico/stdlib.h:12,
                 from D:/vsarm/school/pico_effects/main.c:32:
D:/vsarm/sdk/pico/pico-sdk/src/rp2_common/hardware_timer/include/hardware/timer.h:106:38: note: expected 'absolute_time_t' but argument is of type 'uint64_t' {aka 'long long unsigned int'}
  106 | void busy_wait_until(absolute_time_t t);
      |                      ~~~~~~~~~~~~~~~~^
D:/vsarm/school/pico_effects/main.c: At top level:
I am using the latest GCC compiler.

**Comment by tuupola** [comment]
I think you are compiling in debug mode. This is one of my pet peeves of Pico SDK. It changes datatypes of some functions when enabling debug. It should not be enabled by default so you are probably turning debug mode on by yourself. If something has changed in Pico SDK and debug mode is now on by default, you can turn it off by defining `NDEBUG`.

```
target_compile_definitions(firmware PRIVATE
  NDEBUG
  HAGL_HAL_USE_SINGLE_BUFFER
...
```

**Comment by tuupola** [comment]
I just tested with latest Pico SDK and debug mode is not enabled by default. There was one other minor issue though. I will merge the fix soonish:

https://github.com/tuupola/hagl_pico_mipi/pull/33

**Comment by tuupola** [comment]
No feedback, closing.
